# -*- coding: utf-8 -*-
"""Adivinhe o numero aleatório

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6A9NGbcF0yHsGuQn01Rgy6dnqHdS-E0
"""

# o import random serve pra chamar a biblioteca random
import random
# então eu crio uma lista que vai adicionar um numero nela em todo o intervalo de numeros que o usuario pedir
# uso o inicio pra ser o numero inicial e ser um contador e crio um inicio de verdade escondido pra servir mais pra frente
numero = []
inicio = int(input("Numero inicial: "))
fim = int(input("numero final: "))
inicioreal = inicio

for i in range(inicio,fim):
  numero.append(inicio)
  inicio= inicio + 1
#e uso o random.choice, que é uma função do random que escolhe um item de uma lista, fazendo ele escolher um numero da lista que o usuario criou e atribuindo ele á variavel
adivinhe = (random.choice(numero))
print("Adivinhe!!!")
resposta = int(input())
#depois disso é só configurar a resposta do programa (usando o inicio de verdade que permanece inalterado) pra caso o usuario acerte, erre, fale um numero menor ou maior que o do intervalo
if resposta == adivinhe:
  print("BOAAAA ERA MESMO",resposta,"!!!!!")
elif resposta < inicioreal:
  print("Tá muito baixo, vai mais alto!")
elif resposta > fim:
  print("calma ai amigo, devagar, vamo de novo com um mais baixo")
elif not resposta > fim and not resposta < inicioreal and resposta != adivinhe:
  print("bommm, tenta de novo")

