# -*- coding: utf-8 -*-
"""Matplotlib graphics examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L0XSm7J7pFUxZ8s5PfnGSz_LvIDKeDpT
"""

import matplotlib.pyplot as plt
x = [0, 1, 2, 3, 4]
y = [2, 5, 8, 11, 14]
plt.title('Função de primeiro grau')

plt.plot(x,y, label = "Y(x)", linestyle = '--', marker = "s", color = 'purple')


plt.xlabel("x ")
plt.legend()
plt.ylabel("y")

import matplotlib.pyplot as plt # importa a biblioteca matplotlib e a nomeia como plt
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]#cria lista da questão 2 com 12 valores
y = [25, 20, 12, 10, 15, 18, 12, 14, 14, 15,25, 30 ]#cria lista da questão 4com 12 valores
plt.title('Vendas do ano(artigos de festa)')#nomeia o titulo do grafico

plt.plot(x,y,label= "Desempenho Mensal de Vendas de Artigos de Festa (2023)", linestyle = '-', marker = "s", color = 'Red')#usa o plt plot para alterar os conteurods do grafico, trazendo primeiro as variaveis, em seguida a legenda, depois mudando o estilo de linha, o marcador e por fim a cor


plt.xlabel("Mes")#nomeia o eixo x
plt.legend()#configura para aparecer a legenda
plt.ylabel("Vendas(Unidade de dezena)")#nomeia o eixo y