# -*- coding: utf-8 -*-
"""Matplotlib graphics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETGcheDSD0Obcqm6jQBz70uJFA3q5mnI
"""

import matplotlib as mat
import matplotlib.pyplot as plt
pudim = ['pudim', 'pudim de novo', 'pudim3', 'limao', 'pudim4']
valores = [8, 4, 6, 3, 9]

pud, ax1 = plt.subplots()
ax1.bar(pudim, valores)

ax1.set_xlabel('pudim e etc')
ax1.set_ylabel('valores')

x = [1, 2, 3, 4]
y = [1, 4, 9, 16]

fig, ax = plt.subplots()
ax.plot(x, y, color='blue', linestyle='--', marker='o', label='dados')

ax.set_xlabel('Rótulo X')
ax.set_ylabel('Rótulo Y')
ax.set_title('Título legal')
ax.legend()