# -*- coding: utf-8 -*-
"""Simple functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVWX6EQHhMgF0MIWBr__d_tLKFQSeuOY
"""

def divide(x, y):
  if y != 0:
    result = x / y
  else:
    result = ("erro")
  return result
numerator = 10
denominator = 0
result = divide(numerator , denominator )
print("Result:", result)

def calc_area (length , width ):
  area = length * width
  return area
length = 10
width = 5
area = calc_area (length , width)
print("Area:", area)

def calculo_media (num ):
	no = True
	for num in num:
		if num == str:
			no = False

	if no == True:
		total = sum(num)
		media = total/ len(num)
	else: media = ("erro")
	return media
data = [85, 90, 78, "92", 75, 88]
med = calculo_media (data)
print("Media:", med)

def Soma(a,b):
  return a+b
  a = int(input("Digite o valor de a"))
  b = int(input("Digite o valor de b"))
print(Soma(a,b))

letra = input("Digite uma letra")
if letra in ['a','e','i','o','u']:
  print("vogal")
else:
  print("consoante")